### ISSUE TITLE
Update/configure linter

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol-contracts#10]
One last comment... I promise, linting seems to be broken so there are several lines that need linting (that's another easy QA classic from audits).

_Originally posted by @tmigone in https://github.com/semiotic-ai/timeline-aggregation-protocol-contracts/issues/4#issuecomment-1590237715_

**Comment by ColePBryan** [comment]
@tmigone could you suggest a linter/configuration that would be recommended?

**Comment by tmigone** [comment]
We use solhint with prettier usually, with this config: https://github.com/graphprotocol/contracts/blob/99d7c974f2be4b40aad4598c917f52f7e7efc4f5/.solhint.json

**Comment by ColePBryan** [comment]
Does graph protocol contracts use named mappings at all? It seems solhint does not yet support it:

```
src/AllocationIDTracker.sol
  17:20  error  Parse error: extraneous input 'sender' expecting '=>'
  17:46  error  Parse error: extraneous input 'allocationId' expecting '=>'
  17:67  error  Parse error: extraneous input 'isUsed' expecting ')'

✖ 3 problems (3 errors, 0 warnings)

```

**Comment by tmigone** [comment]
I think you need `solhint@^3.4.0`
