### ISSUE TITLE
Fix front running attack in AllocationIDTracker

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol-contracts#17]
What I would do to fix this is use the collateral contract address as part of the signed message. 

So instead of signing a message with just the `allocationID` the user would have to sign `allocationID,collateralAddress`. 

And here in `verifyProof` you would use `allocationID,msg.sender` when building the `messageHash`. That way  when signing the message you are only allowing the collateral contract to mark the allo as used.

_Originally posted by @tmigone in https://github.com/semiotic-ai/timeline-aggregation-protocol-contracts/pull/4#discussion_r1239847098_

**Comment by tmigone** [comment]
After #15 the proof should also include `sender` so that the message can't be replayed and the allo marked as used on multiple senders with the same proof. The message would then be: `sender,allocationID,collateralAddress`

**Comment by ColePBryan** [comment]
@tmigone I'm not sure if adding sender is needed. Adding collateral address to the proof and using `msg.sender` in allocation ID tracker means that only the address in the proof can mark IDs as used, right? In that case, the contract itself would have to be acting maliciously. If the contract was written maliciously there would be much bigger issues.

Of course, if the gas cost is trivial then we might as well add sender for completeness.

**Comment by tmigone** [comment]
I think you are correct, though since we might reuse the allocation id registry in the future with a different collateral contract it's better to be strict and ensure the security of the alloid contract does not depend on another contract.
