### ISSUE TITLE
N-02 Sender Is Unable to Decrease the Thaw Amount or Cancel the Thaw

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol-contracts#41]
The thaw function in Escrow.sol can only increase the value to be withdrawn from an EscrowAccount . Additionally, the only way to reset the amountThawing for an EscrowAccount to zero is to call withdraw , which will pull the requested GRT from the account. Therefore, there is no way to cancel a thaw action. This can lead to a poor user experience for depositors and accounts.

Consider creating an additional function, cancelThaw , that reduces the amountThawing value for an account to zero.

**Comment by ColePBryan** [comment]
@aasseman @tmigone I added changes to allow cancelling thawing. One feature I'm not sure if we need/want is partial cancelling. If we do want that I need to also know what we should do with thaw counter when that happens. When we increase amount thawing we restart the counter. I'm assuming in this case we would just leave it untouched since it wouldn't negatively impact the receiver.

**Comment by aasseman** [comment]
All of this could be a single function where you can only set the amount thawing (replaces instead increasing the amount), then handle the cases where the amount requested is `0` (cancel), `< prev_thawing_amount` (decrease) , `> prev_thawing_amount` (increase).

**Comment by ColePBryan** [comment]
That's a very good point.  That logic is essentially already there.
