### ISSUE TITLE
Contract should pass redeemed funds through graph contracts instead of directly sending them to receiver

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol-contracts#6]
Context from slack conversation:
>TAP replaces the allocation exchange but not the rebates system, so that means that instead of directly transferring the GRT `Collateral.redeem` should be interacting with `Staking.collect` so that the rebates system kicks in.

**Comment by ColePBryan** [comment]
@tmigone I am running into issues implementing this due to [version compatibility issues] (https://github.com/graphprotocol/contracts/blob/99d7c974f2be4b40aad4598c917f52f7e7efc4f5/contracts/staking/IStaking.sol#L3) . We are using compiler `v. 0.8.18`. I assume the graph contracts won't be moving up in version any time soon, correct? Is there any other way to handle this mismatch? 

[](url)

**Comment by tmigone** [comment]
Wow foundry/forge still doesn't allow multiple solidity versions on the same project, seems crazy given hardhat has had this for ages. 

What you can do is create your own interface file, and simplify it with only the things you need:

```
// IStaking.sol

pragma solidity 0.8.18;

interface IStaking {    
    function collect(uint256 _tokens, address _allocationID) external;
}
```
